# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false

matrix:
  include:
    - r: devel
    - r: release
      env: tibble='CRAN'
      after_success: Rscript -e 'covr::codecov(line_exclusions = c("src/xls.c", "src/xlstool.c", "src/rapidxml.h", "src/rapidxml_print.h", "src/endian.c", "src/ole.c", "src/libxls/brdb.h"))'
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")' -e 'remotes::install_github("tidyverse/tidytemplate")' -e 'remotes::install_cran("tidyverse")' -e 'remotes::install_cran("devtools")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - r: release
      env: tibble='v1.4.2'
      before_script: Rscript -e "remotes::install_version('tibble', '1.4.2')"
    - r: 3.5
    - r: 3.4
    - r: 3.3
    - r: 3.2
    - os: osx
      r: release
      osx_image: xcode8.3
